### ISSUE TITLE
Code download from Packt Publishing

### ISSUE THREAD

**Issue by brownieboy** [emilioicai/react-native-blueprints#1]
I bought your book from Packt Publishing today, and then downloaded the source code from that site.

The source code for Chapter 01 (the shopping app) is missing!   There's no /src folder.  There's no package.json file for Chapter 01 either, so you get an error when you try to run `react-native run-ios` for that one.

Eventually, I found my way here and found the missing code, so problem solved for me.  You need to update the Packt Publishing code though.  In fact, why not just send people to this repository?

**Comment by emilioicai** [comment]
I'm working together with Packt so they can update their materials so any update in this repo would be very valuable for them to track what content is missing from their materials. Thanks for the heads up!
