### ISSUE TITLE
Missing dependency react-native-prompt-android

### ISSUE THREAD

**Issue by brownieboy** [emilioicai/react-native-blueprints#2]
Trying to run the Chapter 1 code gave me an error that the dependency react-native-prompt-android was missing.  A quick `yarn react-native-prompt-android` sorted it out for me.

NB: I was a bit confused to see an error about a missing Android module when I was running on iOS.  Looking through the readme for that module though, it appears to be cross-platform, despite its name.

**Comment by emilioicai** [comment]
thanks! @brownieboy
